name: data-backfill
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=19.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - blas=2.131
  - blas-devel=3.9.0
  - boost-cpp=1.78.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - expat=2.7.1
  - gflags=2.2.2
  - glog=0.5.0
  - icu=70.1
  - krb5=1.21.3
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.71.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - ncurses=6.4
  - nomkl=3.0
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openjdk=8.0.412
  - openssl=3.5.1
  - orc=2.1.1
  - pandas=2.3.1
  - pip=25.1
  - py4j=0.10.9.5
  - pyarrow=19.0.0
  - pyspark=3.3.2
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - re2=2024.07.02
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
